import tiposDeSimbolos from '../../tipos-de-simbolos';

export default {
    add: tiposDeSimbolos.ADICIONAR,
    alter: tiposDeSimbolos.ALTERAR,
    and: tiposDeSimbolos.E,
    auto: tiposDeSimbolos.AUTO,
    between: tiposDeSimbolos.ENTRE,
    column: tiposDeSimbolos.COLUNA,
    constraint: tiposDeSimbolos.RESTRICAO,
    create: tiposDeSimbolos.CRIAR,
    delete: tiposDeSimbolos.EXCLUIR,
    distinct: tiposDeSimbolos.DISTINTO,
    false: tiposDeSimbolos.FALSO,
    foreign: tiposDeSimbolos.ESTRANGEIRA,
    from: tiposDeSimbolos.DE,
    group: tiposDeSimbolos.AGRUPAR,
    identity: tiposDeSimbolos.IDENTIDADE,
    increment: tiposDeSimbolos.INCREMENTO,
    insert: tiposDeSimbolos.INSERIR,
    integer: tiposDeSimbolos.INTEIRO,
    key: tiposDeSimbolos.CHAVE,
    not: tiposDeSimbolos.NAO,
    null: tiposDeSimbolos.NULO,
    order: tiposDeSimbolos.ORDENAR,
    primary: tiposDeSimbolos.PRIMARIA,
    references: tiposDeSimbolos.REFERENCIA,
    select: tiposDeSimbolos.SELECIONAR,
    set: tiposDeSimbolos.DEFINIR,
    string: tiposDeSimbolos.TEXTO,
    table: tiposDeSimbolos.TABELA,
    true: tiposDeSimbolos.VERDADEIRO,
    unique: tiposDeSimbolos.UNICA,
    update: tiposDeSimbolos.ATUALIZAR,
    values: tiposDeSimbolos.VALORES,
    view: tiposDeSimbolos.VISAO,
    where: tiposDeSimbolos.ONDE
}