import tiposDeSimbolos from './tipos-de-simbolos';

export default {
    adicionar: tiposDeSimbolos.ADICIONAR,
    alterar: tiposDeSimbolos.ALTERAR,
    atualizar: tiposDeSimbolos.ATUALIZAR,
    auto: tiposDeSimbolos.AUTO,
    coluna: tiposDeSimbolos.COLUNA,
    chave: tiposDeSimbolos.CHAVE,
    criar: tiposDeSimbolos.CRIAR,
    de: tiposDeSimbolos.DE,
    definir: tiposDeSimbolos.DEFINIR,
    e: tiposDeSimbolos.E,
    em: tiposDeSimbolos.EM,
    excluir: tiposDeSimbolos.EXCLUIR,
    falso: tiposDeSimbolos.FALSO,
    identidade: tiposDeSimbolos.IDENTIDADE,
    incremento: tiposDeSimbolos.INCREMENTO,
    inserir: tiposDeSimbolos.INSERIR,
    inteiro: tiposDeSimbolos.INTEIRO,
    logico: tiposDeSimbolos.LOGICO,
    nao: tiposDeSimbolos.NAO,
    nulo: tiposDeSimbolos.NULO,
    onde: tiposDeSimbolos.ONDE,
    primaria: tiposDeSimbolos.PRIMARIA,
    referencia: tiposDeSimbolos.REFERENCIA,
    renomear: tiposDeSimbolos.RENOMEAR,
    se: tiposDeSimbolos.SE,
    selecionar: tiposDeSimbolos.SELECIONAR,
    tabela: tiposDeSimbolos.TABELA,
    texto: tiposDeSimbolos.TEXTO,
    valores: tiposDeSimbolos.VALORES,
    verdadeiro: tiposDeSimbolos.VERDADEIRO
};
